// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/chunked_widget_to_image.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class WidgetToImageBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  WidgetToImageBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  WidgetToImageBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// 创建图像缓冲区
  ffi.Pointer<ffi.Int64>? create_chunked_widget_to_image(
      ffi.Pointer<ffi.Char> path,
      int width,
      int height,
      int format,
      )
  {
    return _create_chunked_widget_to_image(
      path,
      width,
      height,
      format,
    );
  }

  late final _create_chunked_widget_to_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Int64>? Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.Int,
              ffi.Int)>>('create_chunked_widget_to_image');
  late final _create_chunked_widget_to_image = _create_chunked_widget_to_imagePtr.asFunction<
      ffi.Pointer<ffi.Int64>? Function(
          ffi.Pointer<ffi.Char>, int, int, int)>();

  /// 写入图像数据
  int write_chunked_widget_to_image(ffi.Pointer<ffi.Int64> ctx,ffi.Pointer<ffi.Uint8> pixels,int srcStride,
      int rows,)
  {
    return _write_chunked_widget_to_image(
      ctx,
      pixels,
      srcStride,
      rows,
    );
  }

  late final _write_chunked_widget_to_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Int64>,ffi.Pointer<ffi.Uint8>,
              ffi.Int,ffi.Int)>>('write_chunked_widget_to_image');
  late final _write_chunked_widget_to_image = _write_chunked_widget_to_imagePtr.asFunction<
      int Function(ffi.Pointer<ffi.Int64>,
          ffi.Pointer<ffi.Uint8>,int,int)>();

  /// 保存图像数据
  int save_chunked_widget_to_image(ffi.Pointer<ffi.Int64> ctx)
  {
    return _save_chunked_widget_to_image(ctx);
  }

  late final _save_chunked_widget_to_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Int64>)>>('save_chunked_widget_to_image');
  late final _save_chunked_widget_to_image = _save_chunked_widget_to_imagePtr.asFunction<
      int Function(ffi.Pointer<ffi.Int64>)>();

  /// 将字节数据加载到内存并返回指针
  ffi.Pointer<ffi.Uint8> load_bytes_to_memory(ffi.Pointer<ffi.Uint8> bytes, int size){
    return _load_bytes_to_memory(bytes, size);
  }

  late final _load_bytes_to_memoryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Uint8> Function(ffi.Pointer<ffi.Uint8>, ffi.Uint32)>>('load_bytes_to_memory');
  late final _load_bytes_to_memory = _load_bytes_to_memoryPtr.asFunction<
      ffi.Pointer<ffi.Uint8> Function(ffi.Pointer<ffi.Uint8>, int)>();
}
